## Task

1. Write a NumPy program to test element-wise for NaN of a given array.
2. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.
3. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
4. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
5. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.
6. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
7. In the code cell below, write the code to get and display the 55th row in the dataframe df.
8. In the code cell below write the code to display the first 10 rows of the dataframe <code>df</code>.
9. In the code cell below, select and display the first eight rows from the <code>'Country'</code> and <code>'TB deaths'</code> columns.
10. In the code cell below write code to find all the rows in <code>df</code> where TB deaths exceed 10000.
11. In the code cell below find  all the countries where the Population (1000s) is **less than or equal to** 50000 **or** TB deaths are **greater than or equal to** 20000.

In [29]:
import numpy as np
import pandas as pd

In [3]:
# 1. Write a NumPy program to test element-wise for NaN of a given array.

arr = np.array([1.0, np.nan, 3.4, np.nan, 5.0])
print("Array:", arr)
print("Element-wise NaN test:", np.isnan(arr))

Array: [1.  nan 3.4 nan 5. ]
Element-wise NaN test: [False  True False  True False]

In [5]:
# 2. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.


arr = np.array([1 + 2j, 3, 4.5, 6 + 0j])
print("Is complex:", np.iscomplex(arr))
print("Is real:", np.isreal(arr))
print("Is 3.14 a scalar type?:", np.isscalar(3.14))

Is complex: [ True False False False]
Is real: [False  True  True  True]
Is 3.14 a scalar type?: True

In [7]:
# 3. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

arr1 = np.array([1.0, 2.0, 3.0])
arr2 = np.array([1.00001, 2.00001, 3.00001])
print("Element-wise close:", np.isclose(arr1, arr2))

Element-wise close: [ True  True  True]

In [9]:
# 4. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

x = np.array([1, 5, 9])
y = np.array([3, 5, 7])

print("Greater:", np.greater(x, y))
print("Greater or equal:", np.greater_equal(x, y))
print("Less:", np.less(x, y))
print("Less or equal:", np.less_equal(x, y))

Greater: [False False  True]
Greater or equal: [False  True  True]
Less: [ True False False]
Less or equal: [ True  True False]

In [11]:
# 5. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

x = np.array([1.0, 2.0, 3.0])
y = np.array([1.0, 2.00001, 3.0])

print("Strictly equal:", np.equal(x, y))
print("Equal within tolerance:", np.isclose(x, y))

Strictly equal: [ True False  True]
Equal within tolerance: [ True  True  True]

In [13]:
# 6. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

arr = np.array([1, 7, 13, 105])
print("Memory size of array (in bytes):", arr.nbytes)

Memory size of array (in bytes): 16

In [17]:
# Load Data from cohort database (schema week06). See "Data Access (SQL).md".
import sys, pathlib
_p = pathlib.Path.cwd()
while _p != _p.parent and not (_p / "db" / "dataraflow_db.py").exists():
    _p = _p.parent
sys.path.insert(0, str(_p))
from db.dataraflow_db import run_query

df = run_query("SELECT * FROM week06.who_pop_tb_all")
df

                                Country  Population (1000s)  TB deaths
0                           Afghanistan               30552   13000.00
1                               Albania                3173      20.00
2                               Algeria               39208    5100.00
3                               Andorra                  79       0.26
4                                Angola               21472    6900.00
..                                  ...                 ...        ...
189  Venezuela (Bolivarian Republic of)               30405     480.00
190                            Viet Nam               91680   17000.00
191                               Yemen               24407     990.00
192                              Zambia               14539    3600.00
193                            Zimbabwe               14150    5700.00

[194 rows x 3 columns]

In [19]:
# 7. In the code cell below, write the code to get and display the 55th row in the dataframe df.

df.iloc[54]

Country               El Salvador
Population (1000s)           6340
TB deaths                    61.0
Name: 54, dtype: object

In [21]:
# 8. In the code cell below write the code to display the first 10 rows of the dataframe df.

df.head(10)

               Country  Population (1000s)  TB deaths
0          Afghanistan               30552   13000.00
1              Albania                3173      20.00
2              Algeria               39208    5100.00
3              Andorra                  79       0.26
4               Angola               21472    6900.00
5  Antigua and Barbuda                  90       1.20
6            Argentina               41446     570.00
7              Armenia                2977     170.00
8            Australia               23343      45.00
9              Austria                8495      29.00

In [23]:
# 9. In the code cell below, select and display the first eight rows from the 'Country' and 'TB deaths' columns.

df[['Country', 'TB deaths']].head(8)

               Country  TB deaths
0          Afghanistan   13000.00
1              Albania      20.00
2              Algeria    5100.00
3              Andorra       0.26
4               Angola    6900.00
5  Antigua and Barbuda       1.20
6            Argentina     570.00
7              Armenia     170.00

In [25]:
# 10. In the code cell below write code to find all the rows in df where TB deaths exceed 10000.

df[df['TB deaths'] > 10000]

                              Country  Population (1000s)  TB deaths
0                         Afghanistan               30552    13000.0
13                         Bangladesh              156595    80000.0
36                              China             1393337    41000.0
47   Democratic Republic of the Congo               67514    46000.0
58                           Ethiopia               94101    30000.0
77                              India             1252140   240000.0
78                          Indonesia              249866    64000.0
100                        Madagascar               22925    12000.0
115                        Mozambique               25834    18000.0
116                           Myanmar               53259    26000.0
124                           Nigeria              173615   160000.0
128                          Pakistan              182143    49000.0
134                       Philippines               98394    27000.0
141                Russian Federation              142834    17000.0
159                      South Africa               52776    25000.0
190                          Viet Nam               91680    17000.0

In [27]:
# 11. In the code cell below find all the countries where the Population (1000s) is less than or equal to 50000 or TB deaths are greater than or equal to 20000.

df[(df['Population (1000s)'] <= 50000) | (df['TB deaths'] >= 20000)]

                                Country  Population (1000s)  TB deaths
0                           Afghanistan               30552   13000.00
1                               Albania                3173      20.00
2                               Algeria               39208    5100.00
3                               Andorra                  79       0.26
4                                Angola               21472    6900.00
..                                  ...                 ...        ...
188                             Vanuatu                 253      16.00
189  Venezuela (Bolivarian Republic of)               30405     480.00
191                               Yemen               24407     990.00
192                              Zambia               14539    3600.00
193                            Zimbabwe               14150    5700.00

[180 rows x 3 columns]

## Assignment

1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.


2. Write a Python program to convert a Panda module Series to Python list and it's type.


3. Write a Python program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


4. Write a Python program to get the largest integer smaller or equal to the division of the inputs.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


5. Write a Python program to convert a dictionary to a Pandas series.
Sample Series:
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a 100
b 200
c 300
d 400
e 800
dtype: int64


6. Write a Python program to convert a NumPy array to a Pandas series.
Sample Series:
NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0 10
1 20
2 30
3 40
4 50
dtype: int64


7. Write a Python program to change the data type of given a column or a Series.
Sample Series:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Change the said data type to numeric:
0 100.00
1 200.00
2 NaN
3 300.12
4 400.00
dtype: float64


8. Write a Python Pandas program to convert the first column of a DataFrame as a Series.
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
1st column as a Series:
0 1
1 2
2 3
3 4
4 7
5 11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


9. Write a Pandas program to convert a given Series to an array.
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']



 
10. Write a Pandas program to convert Series of lists to one Series.
Sample Output:
Original Series of list
0 [Red, Green, White]
1 [Red, Black]
2 [Yellow]
dtype: object
One Series
0 Red
1 Green
2 White
3 Red
4 Black
5 Yellow
dtype: object


11. Write a Pandas program to sort a given Series.
Sample Output:
Original Data Series: 0 100
1 200
2 python
3 300.12
4 400
dtype: object
0 100
1 200
3 300.12
4 400
2 python
dtype: object


12. Write a Pandas program to add some data to an existing Series.
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Data Series after adding some data:
0 100
1 200
2 python
3 300.12
4 400
0 500
1 php
dtype: object

In [31]:
# 1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

ds = pd.Series([10, 20, 30, 40, 50])
print(ds)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [33]:
# 2. Write a Python program to convert a Panda module Series to Python list and it's type.

ds = pd.Series([10, 20, 30, 40, 50])
python_list = ds.tolist()

print("Converted List:", python_list)
print("Type:", type(python_list))

Converted List: [10, 20, 30, 40, 50]
Type: <class 'list'>

In [35]:
# 3. Write a Python program to add, subtract, multiple and divide two Pandas Series. Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

print("Addition:\n", s1 + s2)
print("\nSubtraction:\n", s1 - s2)
print("\nMultiplication:\n", s1 * s2)
print("\nDivision:\n", s1 / s2)

Addition:
 0     3
1     7
2    11
3    15
4    19
dtype: int64

Subtraction:
 0    1
1    1
2    1
3    1
4    1
dtype: int64

Multiplication:
 0     2
1    12
2    30
3    56
4    90
dtype: int64

Division:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [37]:
# 4. Write a Python program to get the largest integer smaller or equal to the division of the inputs. Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

result = s1 // s2
print(result)

0    2
1    1
2    1
3    1
4    1
dtype: int64

In [39]:
# 5. Write a Python program to convert a dictionary to a Pandas series. Sample Series: Original dictionary: {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800} Converted series: a 100 b 200 c 300 d 400 e 800 dtype: int64

d_dict = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
new_series = pd.Series(d_dict)

print("Original dictionary:", d_dict)
print("Converted series:\n", new_series)

Original dictionary: {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
 a    100
b    200
c    300
d    400
e    800
dtype: int64

In [41]:
# 6. Write a Python program to convert a NumPy array to a Pandas series. Sample Series: NumPy array: [10 20 30 40 50] Converted Pandas series: 0 10 1 20 2 30 3 40 4 50 dtype: int64

np_array = np.array([10, 20, 30, 40, 50])
new_series = pd.Series(np_array)

print("NumPy array:", np_array)
print("Converted Pandas series:\n", new_series)

NumPy array: [10 20 30 40 50]
Converted Pandas series:
 0    10
1    20
2    30
3    40
4    50
dtype: int32

In [43]:
# 7. Write a Python program to change the data type of given a column or a Series. Sample Series: Original Data Series: 0 100 1 200 2 python 3 300.12 4 400 dtype: object Change the said data type to numeric: 0 100.00 1 200.00 2 NaN 3 300.12 4 400.00 dtype: float64

s = pd.Series(['100', '200', 'python', '300.12', '400'])
numeric_series = pd.to_numeric(s, errors='coerce')

print("Original Data Series:\n", s)
print("\nChange the said data type to numeric:\n", numeric_series)

Original Data Series:
 0       100
1       200
2    python
3    300.12
4       400
dtype: object

Change the said data type to numeric:
 0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [45]:
# 8. Write a Python Pandas program to convert the first column of a DataFrame as a Series. Sample Output: Original DataFrame col1 col2 col3 0 1 4 7 1 2 5 5 2 3 6 8 3 4 9 12 4 7 5 1 5 11 0 11 1st column as a Series: 0 1 1 2 2 3 3 4 4 7 5 11 Name: col1, dtype: int64 <class 'pandas.core.series.Series'>

df = pd.DataFrame({
    'col1': [1, 2, 3, 4, 7, 11],
    'col2': [4, 5, 6, 9, 5, 0],
    'col3': [7, 5, 8, 12, 1, 11]
})

first_col = df.iloc[:, 0]

print("Original DataFrame:\n", df)
print("\n1st column as a Series:\n", first_col)
print("Type:", type(first_col))

Original DataFrame:
    col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

1st column as a Series:
 0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
Type: <class 'pandas.core.series.Series'>

In [47]:
# 9. Write a Pandas program to convert a given Series to an array. Sample Output: Original Data Series: 0 100 1 200 2 python 3 300.12 4 400 dtype: object Series to an array ['100' '200' 'python' '300.12' '400']

s = pd.Series(['100', '200', 'python', '300.12', '400'])
arr = s.to_numpy()

print("Original Data Series:\n", s)
print("\nSeries to an array:", arr)

Original Data Series:
 0       100
1       200
2    python
3    300.12
4       400
dtype: object

Series to an array: ['100' '200' 'python' '300.12' '400']

In [49]:
# 10. Write a Pandas program to convert Series of lists to one Series. Sample Output: Original Series of list 0 [Red, Green, White] 1 [Red, Black] 2 [Yellow] dtype: object One Series 0 Red 1 Green 2 White 3 Red 4 Black 5 Yellow dtype: object

s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']
])

flat_series = pd.Series([item for sublist in s for item in sublist])

print("Original Series of list:\n", s)
print("\nOne Series:\n", flat_series)

Original Series of list:
 0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

One Series:
 0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

In [51]:
# 11. Write a Pandas program to sort a given Series. Sample Output: Original Data Series: 0 100 1 200 2 python 3 300.12 4 400 dtype: object 0 100 1 200 3 300.12 4 400 2 python dtype: object

s = pd.Series(['100', '200', 'python', '300.12', '400'])
sorted_s = s.sort_values()

print("Original Data Series:\n", s)
print("\nSorted Series:\n", sorted_s)

Original Data Series:
 0       100
1       200
2    python
3    300.12
4       400
dtype: object

Sorted Series:
 0       100
1       200
3    300.12
4       400
2    python
dtype: object

In [53]:
# 12. Write a Pandas program to add some data to an existing Series. Sample Output: Original Data Series: 0 100 1 200 2 python 3 300.12 4 400 dtype: object Data Series after adding some data: 0 100 1 200 2 python 3 300.12 4 400 0 500 1 php dtype: object

s = pd.Series(['100', '200', 'python', '300.12', '400'])
additional_data = pd.Series(['500', 'php'])

new_s = pd.concat([s, additional_data], ignore_index=True)

print("Original Data Series:\n", s)
print("\nData Series after adding some data:\n", new_s)

Original Data Series:
 0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
 0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object

## Assessment

#### The datasets now live in the cohort database (schema `week06`)

The six airport weather datasets are the tables:

```
week06.beijing_pek_2014, week06.brasilia_bsb_2014, week06.capetown_cpt_2014,
week06.delhi_del_2014,   week06.london_2014,       week06.moscow_svo_2014
```

Pull them with SQL and explore them — see **`Data Access (SQL).md`** in this week's folder
for the connection snippet and worked examples. For example:

```python
from db.dataraflow_db import run_query
london = run_query("SELECT * FROM week06.london_2014")
```

Run your analysis on them, and detail your findings below as much as you can.

---
## SQL Assessment (Intermediate SQL)

This part tests what you learnt in **`4-Intermediate SQL/Intermediate SQL.ipynb`**. Every task runs against the
**live cohort database** using your **read-only** account.

**How it works**
1. Run the **SQL setup** cell below first (and again after restarting the kernel).
2. In each task cell, write your query **between the triple quotes**, then run the cell.
3. `answer(...)` runs your query, shows the result, and tells you if it's ✅ correct. If not, it tells you
   whether the **shape** (rows × columns) is right, so you know where to look.
4. Match the **column order**, **sort order** and **rounding** asked for. Column *names* aren't checked,
   but use the names given.
5. Run `sql_score()` at the end to see your SQL score.

Writes are blocked: the database is read-only, so build everything inside your `SELECT` (CTEs are your workspace).

In [87]:
# --- SQL setup: run this cell first (don't edit it) ---
import sys, pathlib, re, json, hashlib, datetime, math
_p = pathlib.Path.cwd()
while _p != _p.parent and not (_p / "db" / "dataraflow_db.py").exists():
    _p = _p.parent
sys.path.insert(0, str(_p))
from db.dataraflow_db import run_query
import pandas as pd

_BLOCKED = re.compile(r"\b(INSERT|UPDATE|DELETE|MERGE|DROP|ALTER|CREATE|TRUNCATE|EXEC|EXECUTE|GRANT|REVOKE|DENY|INTO|BACKUP|RESTORE)\b", re.I)

def _strip(sql):
    sql = re.sub(r"'([^']|'')*'", "''", sql)
    sql = re.sub(r"--[^\n]*", "", sql)
    return re.sub(r"/\*.*?\*/", "", sql, flags=re.S)

def q(sql):
    """Run a read-only query and return a DataFrame (same helper as the Intermediate SQL notebook)."""
    hit = _BLOCKED.search(_strip(sql))
    if hit:
        raise PermissionError(f"'{hit.group(0).upper()}' is not allowed: the database is read-only.")
    return run_query(sql)

_DATE = re.compile(r"^\d{4}-\d{1,2}-\d{1,2}")

def _norm(v):
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return None
    if isinstance(v, (datetime.date, datetime.datetime, pd.Timestamp)):
        return pd.Timestamp(v).date().isoformat()
    if isinstance(v, str):
        v = v.strip()
        if _DATE.match(v):
            try:
                return pd.Timestamp(v).date().isoformat()
            except ValueError:
                pass
        return v
    try:
        return round(float(v), 2)
    except (TypeError, ValueError):
        return str(v)

def _fingerprint(df):
    rows = [[_norm(v) for v in row] for row in df.itertuples(index=False)]
    return hashlib.sha256(json.dumps(rows).encode()).hexdigest()

# expected answers are stored only as fingerprints, so this notebook doesn't give them away
EXPECTED = {
 "s01": [
  [
   8,
   2
  ],
  "0ba3b4c0210bb324982933cd308c7ff0bb3fbbea32fc6646d9e9e2a9bb14df70"
 ],
 "s02": [
  [
   1,
   3
  ],
  "1512ef1d7254b2206516b1f4bb9dea659b456cab8b80402f5bf67de186fc7fff"
 ],
 "s03": [
  [
   3,
   4
  ],
  "607a2a3b80c9fdc820855d34f48730b445d9437842569c3d7406962b2ec71409"
 ],
 "s04": [
  [
   26,
   2
  ],
  "2fe50527877da0fd0064e1512aa038aa08109668d30b5e0083874edc03b773cf"
 ],
 "s05": [
  [
   5,
   2
  ],
  "8d5b93be4960cbb6acd605b1fa741b3be8bbe6c44c5fb19b843daf38737e1ab1"
 ],
 "s06": [
  [
   1,
   1
  ],
  "c3c32ce95ec239c2ac639584925dced87cfb17b11bee9b738bc7ed104c2ce931"
 ],
 "s07": [
  [
   6,
   2
  ],
  "8450a870c23b5bfab2a420e0a10a1b534e113a7c4acd0be5b90060f8bebe4e2c"
 ],
 "s08": [
  [
   12,
   3
  ],
  "27236391b69c4478be3e09fa08b89fe7c5acd46b03bb5a934c14e6e122bddb0d"
 ],
 "s09": [
  [
   12,
   3
  ],
  "880e60a4b694da3e224b104c67139870b74671f6ef86f16b9d5ac46c2d81ad04"
 ],
 "s10": [
  [
   3,
   4
  ],
  "9b15fac9c91f6a72150b0c1705f96f0e8281cbe86e49c56d49f37a3d885328ac"
 ]
}
TASKS = {
 "s01": "Exploring the schema",
 "s02": "Filtering & NULLs",
 "s03": "CASE & conditional aggregation",
 "s04": "GROUP BY + HAVING",
 "s05": "JOIN across sources",
 "s06": "Anti-join",
 "s07": "UNION ALL",
 "s08": "CTE + window ranking",
 "s09": "Running total (window)",
 "s10": "Business question"
}
RESULTS = {}

def answer(task, sql):
    """Run your query for a task, show the result, and check it."""
    shape, fp = EXPECTED[task]
    if not _strip(sql).strip():
        RESULTS[task] = None
        print(f"⏳ {task}: not attempted yet. Write your query between the triple quotes.")
        return
    try:
        df = q(sql)
    except Exception as err:
        RESULTS[task] = False
        print(f"❌ {task}: the query failed.\n   {type(err).__name__}: {str(err)[:300]}")
        return
    display(df.head(15))
    ok = _fingerprint(df) == fp
    RESULTS[task] = ok
    if ok:
        print(f"✅ {task}: correct!")
        return
    print(f"❌ {task}: not quite. Expected {shape[0]} row(s) × {shape[1]} column(s); "
          f"you returned {df.shape[0]} × {df.shape[1]}.")
    if df.shape == tuple(shape):
        print("   The shape is right, so check: column order, sort order, rounding, and filters "
              "(NULLs, the 'World' row, etc.).")

def sql_score():
    """Print your SQL score table."""
    rows = []
    for task, title in TASKS.items():
        r = RESULTS.get(task)
        rows.append([task, title, "✅" if r else ("not attempted" if r is None else "❌")])
    table = pd.DataFrame(rows, columns=["Task", "Topic", "Result"])
    print(table.to_string(index=False))
    print(f"\nSQL score: {sum(1 for r in RESULTS.values() if r)} / {len(TASKS)}")

print(f"SQL setup done: {len(TASKS)} tasks. Connected as:",
      run_query("SELECT CURRENT_USER AS u").u[0])

SQL setup done: 10 tasks. Connected as: intern_readonly

### SQL Task 1 · Exploring the schema
Using `INFORMATION_SCHEMA.COLUMNS`, list every table in the **`week06`** schema with **how many columns** it has.

**Return:** `table_name`, `n_columns`, sorted by `table_name` (A→Z).
*Revisit: Intermediate SQL §1.*

In [57]:
SQL_01 = """
SELECT TABLE_NAME AS table_name, COUNT(*) AS n_columns
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'week06'
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;
"""
answer("s01", SQL_01)

          table_name  n_columns
0   beijing_pek_2014         23
1  brasilia_bsb_2014         23
2  capetown_cpt_2014         23
3     delhi_del_2014         23
4        london_2014         23
5    moscow_svo_2014         23
6     who_pop_tb_all          3
7    who_pop_tb_some          3

✅ s01: correct!

### SQL Task 2 · Filtering & NULLs
For **London** (`week06.london_2014`), return **one row** with three counts:
1. `no_event_days`: days with **no event recorded**
2. `rain_days`: days whose event mentions **Rain** anywhere (e.g. `Rain`, `Fog-Rain`, `Rain-Thunderstorm`)
3. `wet_but_no_event_days`: days with **no event recorded** but `Precipitationmm > 0`

⚠️ The events column name starts with a **space**: `[ Events]`. And remember, `= NULL` never matches.
*Revisit: §1.2, §3.2, §3.3.*

In [59]:
SQL_02 = """
SELECT 
    SUM(CASE WHEN [ Events] IS NULL OR [ Events] = '' THEN 1 ELSE 0 END) AS no_event_days,
    SUM(CASE WHEN [ Events] LIKE '%Rain%' THEN 1 ELSE 0 END) AS rain_days,
    SUM(CASE WHEN ([ Events] IS NULL OR [ Events] = '') AND [Precipitationmm] > 0 THEN 1 ELSE 0 END) AS wet_but_no_event_days
FROM week06.london_2014
"""
answer("s02", SQL_02)

   no_event_days  rain_days  wet_but_no_event_days
0            114        238                      6

✅ s02: correct!

### SQL Task 3 · CASE & conditional aggregation
From `week16.customer_churn_prediction`, for each `Contract_Type` return: number of `customers`, number
`churned` (`Churn = 1`), and `churn_rate_pct` (percentage, **rounded to 1 decimal place**).

**Return:** `Contract_Type`, `customers`, `churned`, `churn_rate_pct`, sorted by `churn_rate_pct` (highest first).
⚠️ Watch out for the integer-division trap. *Revisit: §4.4, §5.2.*

In [61]:
SQL_03 = """
SELECT 
    Contract_Type,
    COUNT(*) AS customers,
    SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END) AS churned,
    ROUND(100.0 * SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END) / COUNT(*), 1) AS churn_rate_pct
FROM week16.customer_churn_prediction
GROUP BY Contract_Type
ORDER BY churn_rate_pct DESC;
"""
answer("s03", SQL_03)

    Contract_Type  customers  churned  churn_rate_pct
0  Month-to-Month        158       91            57.6
1        One Year        165       89            53.9
2        Two Year        177       48            27.1

✅ s03: correct!

### SQL Task 4 · GROUP BY + HAVING
From `week09.comtrade_milk_uk_monthly_14`, find the partner countries the UK **exported** milk to in
**all 12 months** of 2014, with the **total export value**.

**Return:** `Partner`, `total_exports_usd`, sorted by `total_exports_usd` (highest first).
⚠️ Exclude the `'World'` total row. *Revisit: §6.2.*

In [79]:
from db.dataraflow_db import run_query

df_sample = run_query("SELECT TOP 1 * FROM week09.comtrade_milk_uk_monthly_14")
print("Columns:", df_sample.columns.tolist())

Columns: ['Classification', 'Year', 'Period', 'Period Desc.', 'Aggregate Level', 'Is Leaf Code', 'Trade Flow Code', 'Trade Flow', 'Reporter Code', 'Reporter', 'Reporter ISO', 'Partner Code', 'Partner', 'Partner ISO', '2nd Partner Code', '2nd Partner', '2nd Partner ISO', 'Customs Proc. Code', 'Customs', 'Mode of Transport Code', 'Mode of Transport', 'Commodity Code', 'Commodity', 'Qty Unit Code', 'Qty Unit', 'Qty', 'Alt Qty Unit Code', 'Alt Qty Unit', 'Alt Qty', 'Netweight (kg)', 'Gross weight (kg)', 'Trade Value (US$)', 'CIF Trade Value (US$)', 'FOB Trade Value (US$)', 'Flag']

In [81]:
SQL_04 = """
SELECT Partner, SUM([Trade Value (US$)]) AS total_exports_usd
FROM week09.comtrade_milk_uk_monthly_14
WHERE Partner <> 'World'
GROUP BY Partner
HAVING COUNT(DISTINCT Period) = 12
ORDER BY total_exports_usd DESC;
"""
answer("s04", SQL_04)

                 Partner  total_exports_usd
0                Ireland          595544327
1            Netherlands          140858317
2                 France          139631158
3                Germany          112709333
4                Algeria           93753841
5                Belgium           87681752
6                Denmark           33443099
7                  China           27317861
8                  Spain           20468079
9   China, Hong Kong SAR           19847947
10                Poland           16556286
11               Nigeria           12932371
12                Guinea           12018176
13               Lebanon           10400613
14                Sweden            6468256

❌ s04: not quite. Expected 26 row(s) × 2 column(s); you returned 30 × 2.

### SQL Task 5 · JOIN across two sources
Join WHO TB data (`week06.who_pop_tb_all`) with World Bank population (`week08.wb_pop_2013`) on the country
name. Compute **TB deaths per 100,000 people** using the **World Bank** population (`[SP.POP.TOTL]`),
**rounded to 1 decimal place**.

**Return:** the **top 5** countries: `Country`, `tb_deaths_per_100k`, highest first.
*Revisit: §7.2–7.3.*

In [83]:
SQL_05 = """
SELECT TOP 5 
    a.Country,
    ROUND(100000.0 * a.[TB deaths] / b.[SP.POP.TOTL], 1) AS tb_deaths_per_100k
FROM week06.who_pop_tb_all a
JOIN week08.wb_pop_2013 b ON a.Country = b.Country
ORDER BY tb_deaths_per_100k DESC;
"""
answer("s05", SQL_05)

       Country  tb_deaths_per_100k
0     Djibouti               100.6
1      Nigeria                92.6
2    Swaziland                88.0
3  Timor-Leste                83.9
4      Somalia                75.0

✅ s05: correct!

### SQL Task 6 · Anti-join
How many WHO countries in `week06.who_pop_tb_all` have **no matching country name** in `week08.wb_pop_2013`?

**Return:** one row, one column (`who_countries_without_wb_match`).
*Revisit: §7.4. Bonus thought: why do these countries fail to match?*

In [89]:
SQL_06 = """
SELECT COUNT(*) AS who_countries_without_wb_match
FROM week06.who_pop_tb_all a
LEFT JOIN week08.wb_pop_2013 b ON a.Country = b.Country
WHERE b.Country IS NULL;
"""
answer("s06", SQL_06)

   who_countries_without_wb_match
0                              28

✅ s06: correct!

### SQL Task 7 · UNION ALL
Stack the **six** city weather tables in `week06` and compute each city's **average `Mean TemperatureC`**
for 2014, **rounded to 1 decimal place**. Use exactly these city labels:
`'Beijing'`, `'Brasilia'`, `'Cape Town'`, `'Delhi'`, `'London'`, `'Moscow'`.

**Return:** `city`, `avg_mean_temp_c`, sorted by `city` (A→Z).
⚠️ `Mean TemperatureC` is stored as a whole number, so watch the integer-division trap. *Revisit: §8.1–8.2.*

In [91]:
SQL_07 = """
WITH all_cities AS (
    SELECT 'Beijing' AS city, [Mean TemperatureC] FROM week06.beijing_pek_2014
    UNION ALL
    SELECT 'Brasilia' AS city, [Mean TemperatureC] FROM week06.brasilia_bsb_2014
    UNION ALL
    SELECT 'Cape Town' AS city, [Mean TemperatureC] FROM week06.capetown_cpt_2014
    UNION ALL
    SELECT 'Delhi' AS city, [Mean TemperatureC] FROM week06.delhi_del_2014
    UNION ALL
    SELECT 'London' AS city, [Mean TemperatureC] FROM week06.london_2014
    UNION ALL
    SELECT 'Moscow' AS city, [Mean TemperatureC] FROM week06.moscow_svo_2014
)
SELECT 
    city,
    ROUND(AVG(1.0 * [Mean TemperatureC]), 1) AS avg_mean_temp_c
FROM all_cities
GROUP BY city
ORDER BY city ASC;
"""
answer("s07", SQL_07)

        city  avg_mean_temp_c
0    Beijing             13.4
1   Brasilia             22.9
2  Cape Town             17.6
3      Delhi             13.7
4     London             12.3
5     Moscow              6.0

✅ s07: correct!

### SQL Task 8 · CTE + window ranking (top-1 per group)
For **London**, find the **hottest day of each month** (highest `Max TemperatureC`). If two days tie,
take the **earlier** date.

**Return:** `month_no`, `day` (a real **date**, convert `GMT` with `TRY_CONVERT(date, GMT)`), `max_temp`,
sorted by `month_no`. *Revisit: §10, §11.3.*

In [93]:
SQL_08 = """
WITH ranked_days AS (
    SELECT 
        MONTH(TRY_CONVERT(date, GMT)) AS month_no,
        TRY_CONVERT(date, GMT) AS day,
        [Max TemperatureC] AS max_temp,
        ROW_NUMBER() OVER (
            PARTITION BY MONTH(TRY_CONVERT(date, GMT)) 
            ORDER BY [Max TemperatureC] DESC, TRY_CONVERT(date, GMT) ASC
        ) AS rn
    FROM week06.london_2014
)
SELECT month_no, day, max_temp
FROM ranked_days
WHERE rn = 1
ORDER BY month_no ASC;
"""
answer("s08", SQL_08)

    month_no         day  max_temp
0          1  2014-01-05        12
1          2  2014-02-24        14
2          3  2014-03-09        19
3          4  2014-04-01        19
4          5  2014-05-19        26
5          6  2014-06-09        26
6          7  2014-07-18        30
7          8  2014-08-06        26
8          9  2014-09-18        26
9         10  2014-10-31        23
10        11  2014-11-01        18
11        12  2014-12-17        13

✅ s08: correct!

### SQL Task 9 · Running total
From `week09.comtrade_milk_uk_monthly_14`, compute the UK's **total milk exports per month** (exclude `'World'`)
and a **year-to-date running total**.

**Return:** `Period`, `exports_usd`, `ytd_exports_usd`, sorted by `Period`. *Revisit: §11.4–11.5.*

In [95]:
SQL_09 = """
WITH monthly_exports AS (
    SELECT 
        Period,
        SUM([Trade Value (US$)]) AS exports_usd
    FROM week09.comtrade_milk_uk_monthly_14
    WHERE Partner <> 'World'
    GROUP BY Period
)
SELECT 
    Period,
    exports_usd,
    SUM(exports_usd) OVER (ORDER BY Period ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS ytd_exports_usd
FROM monthly_exports
ORDER BY Period ASC;
"""
answer("s09", SQL_09)

    Period  exports_usd  ytd_exports_usd
0   201401    139512730        139512730
1   201402    111789783        251302513
2   201403    131100878        382403391
3   201404    139406385        521809776
4   201405    144276259        666086035
5   201406    144420204        810506239
6   201407    117675467        928181706
7   201408    102032536       1030214242
8   201409    117302838       1147517080
9   201410    113368960       1260886040
10  201411    106377173       1367263213
11  201412     95273664       1462536877

❌ s09: not quite. Expected 12 row(s) × 3 column(s); you returned 12 × 3.
   The shape is right, so check: column order, sort order, rounding, and filters (NULLs, the 'World' row, etc.).

### SQL Task 10 · Business question
The Head of Credit asks: *"How does the approval rate vary by property area and credit history?"*
Using `week17.loan_approval_prediction`, return one row per `Property_Area` × `Credit_History` combination
that exists in the data, with the number of `applications` and the `approval_rate_pct` (rounded to 1 decimal).

**Return:** `Property_Area`, `Credit_History`, `applications`, `approval_rate_pct`, sorted by `Property_Area`
then `Credit_History`. Then answer reflection question 3 below about what you see.

In [99]:
from db.dataraflow_db import run_query

df_sample = run_query("SELECT TOP 1 * FROM week17.loan_approval_prediction")
print("Columns:", df_sample.columns.tolist())

Columns: ['Application_ID', 'Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Applicant_Income', 'Coapplicant_Income', 'Loan_Amount', 'Loan_Term', 'Credit_History', 'Property_Area', 'Previous_Loan_Status', 'Employment_Years', 'Age', 'Loan_Approved']

In [101]:
SQL_10 = """
SELECT 
    Property_Area,
    Credit_History,
    COUNT(*) AS applications,
    ROUND(100.0 * SUM(CASE WHEN Loan_Approved = 1 THEN 1 ELSE 0 END) / COUNT(*), 1) AS approval_rate_pct
FROM week17.loan_approval_prediction
GROUP BY Property_Area, Credit_History
ORDER BY Property_Area ASC, Credit_History ASC;
"""
answer("s10", SQL_10)

  Property_Area  Credit_History  applications  approval_rate_pct
0         Rural               0           166                0.0
1     Semiurban               1           167              100.0
2         Urban               1           167              100.0

✅ s10: correct!

### SQL reflection
Answer in the cell below (2–3 sentences each):

1. In Task 3 or Task 7, what would `AVG(Churn)` or `AVG([Mean TemperatureC])` return **without** converting to a
   decimal first, and why?
2. In Task 6, why do those countries fail to match? How would you fix this in a real project?
3. Look at your Task 10 result. What is **suspicious** about it? What would you tell the Head of Credit before
   anyone trains a model on this data?

**My answers:**

1. Without multiplying by a float or converting to a decimal first, SQL Server treats the operation using integer division rules, truncating any fractional remainder. For AVG(Churn) (binary 0 and 1), it would truncate any average below 1.0 down to 0, and for [Mean TemperatureC], it would strip all decimal precision and return whole numbers only.
   
2. Those countries fail to match due to inconsistent naming conventions, punctuation differences, and formatting disparities between the two independent sources (e.g., "United States" versus "United States of America", or official UN prefixes). In a real project, this is best resolved by joining on standardized ISO 3166-1 alpha-3 country codes rather than raw text names, or by constructing a lookup/mapping table for edge-case name variations.

3. What often stands out in loan approval datasets is extreme feature dominance or complete separation, where a variable like Credit_History predicts the outcome with near 100% determinism. I would advise the Head of Credit to check for target leakage or over-reliance on a single proxy metric, as models trained on overly deterministic synthetic or raw credit data can fail to generalize in production or create unfair systemic biases.

### SQL score
Run this when you're done.

In [107]:
sql_score()

---
## 📰 Article Link

Write a **detailed article** about this week's work. It should cover:

- **What you learnt:** the key concepts, tools and techniques from this week.
- **What you solved:** the tasks and projects you worked on, and how you approached them.
- **Challenges you faced:** what was hard, confusing or didn't work at first.
- **How you overcame them:** what you tried, what finally worked, and what you'd do differently.
- **Anything else you want to share:** insights, results, visuals, or advice for others learning this.

Publish it, then paste the article's **URL** in the empty cell below (double-click the cell to edit it).